<a href="https://colab.research.google.com/github/edoruin/Data_cleanned_practice/blob/main/Cleaning_TITANIC_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Stadistic Descriptive

In [ ]:
test = pd.read_csv('/content/drive/MyDrive/data practice/data_bases/Titanic/test.csv')
train = pd.read_csv('/content/drive/MyDrive/data practice/data_bases/Titanic/train.csv')


train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
#i no need name column for this i going remove the column
train.drop(['Name'],axis=1,inplace=True)
test.drop(['Name'], axis = 1, inplace=True)

In [ ]:
#cleaning categoricals variables with SimpleImputer
from sklearn.impute import SimpleImputer

cat_imputer = SimpleImputer(strategy='most_frequent')

cat_cols = train.select_dtypes(include='object').columns #take de cols names


train[cat_cols] = cat_imputer.fit_transform(train[cat_cols]) #applied the SimpleImputer
test[cat_cols] = cat_imputer.fit_transform(test[cat_cols])

In [ ]:
#drop of nan values in numeric cols

#llenar los valores perdidos
train['Age'] = train['Age'].fillna(train['Age'].mean())
train['Age'] = train['Age'].astype('int')

test['Age'] = test['Age'].fillna(test['Age'].mean())
test['Age'] = test['Age'].astype('int')

In [ ]:
#ONE-HOT encoding
from sklearn.preprocessing import OneHotEncoder

OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False) #storage the method of one-hot encoding in one variable

cat_cols = train[['Sex','Embarked']].columns #name of columns to use
#0,1 = man and woman/ 2,3,4 = S,C,Q

Encoder_train = pd.DataFrame(OH_encoder.fit_transform(train[cat_cols])) #encoded
Encoder_test = pd.DataFrame(OH_encoder.fit_transform(test[cat_cols]))

Encoder_train.index = train.index #add again the index
Encoder_test.index = test.index

#drop the categoricals variables that will be changes
num_X_train = train.drop(cat_cols, axis=1)
num_X_test = test.drop(cat_cols, axis=1)

#apply One-HOT encoding
data_train = pd.concat([num_X_train, Encoder_train], axis=1)
data_test = pd.concat([num_X_test, Encoder_test], axis=1)

# Ensure all columns have string type
data_train.columns = data_train.columns.astype(str)
data_test.columns = data_test.columns.astype(str)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [ ]:
#this time i going to drop cabin and ticket but the prox i going to cleanned this columns

data_train = data_train.drop(['Ticket','Cabin'],axis =1)
data_test = data_test.drop(['Ticket','Cabin'],axis =1)

In [ ]:
#download the datasets cleaned

data_train.to_csv('/content/drive/MyDrive/data practice/data_bases/V_train.csv')
data_test.to_csv('/content/drive/MyDrive/data practice/data_bases/V_test.csv')